services:
  backend:
    container_name: rentease-backend
    restart: unless-stopped
    networks:
      - rentease-network

  frontend:
    container_name: rentease-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - rentease-network

networks:
  rentease-network:
    driver: bridge