apiVersion: v1
kind: ConfigMap

metadata:
  name: rentease-config
  namespace: rentease
  labels:
    app.kubernetes.io/name: rentease
    app.kubernetes.io/part-of: rentease
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl

data:
  PORT: "8000"
  NODE_ENV: "production"